# [[keybindings]]
# chars = "\u001Ba"
# key = "A"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bb"
# key = "B"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bc"
# key = "C"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bd"
# key = "D"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Be"
# key = "E"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bf"
# key = "F"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bg"
# key = "G"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bh"
# key = "H"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bi"
# key = "I"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bj"
# key = "J"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bk"
# key = "K"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bl"
# key = "L"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bm"
# key = "M"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bn"
# key = "N"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bo"
# key = "O"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bp"
# key = "P"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bq"
# key = "Q"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Br"
# key = "R"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bs"
# key = "S"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bt"
# key = "T"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bu"
# key = "U"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bv"
# key = "V"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bw"
# key = "W"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bx"
# key = "X"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001By"
# key = "Y"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001Bz"
# key = "Z"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001BA"
# key = "A"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BB"
# key = "B"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BC"
# key = "C"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BD"
# key = "D"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BE"
# key = "E"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BF"
# key = "F"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BG"
# key = "G"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BH"
# key = "H"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BI"
# key = "I"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BJ"
# key = "J"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BK"
# key = "K"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BL"
# key = "L"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BM"
# key = "M"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BN"
# key = "N"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BO"
# key = "O"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BP"
# key = "P"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BQ"
# key = "Q"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BR"
# key = "R"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BS"
# key = "S"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BT"
# key = "T"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BU"
# key = "U"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BV"
# key = "V"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BW"
# key = "W"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BX"
# key = "X"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BY"
# key = "Y"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001BZ"
# key = "Z"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001B1"
# key = "Key1"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001B2"
# key = "Key2"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001B3"
# key = "Key3"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001B4"
# key = "Key4"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001B5"
# key = "Key5"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001B6"
# key = "Key6"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001B7"
# key = "Key7"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001B8"
# key = "Key8"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001B9"
# key = "Key9"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001B0"
# key = "Key0"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u0000"
# key = "Space"
# mods = "Control"
#
# [[keybindings]]
# chars = "\u001B`"
# key = "Grave"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001B~"
# key = "Grave"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001B."
# key = "Period"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001B*"
# key = "Key8"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001B#"
# key = "Key3"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001B>"
# key = "Period"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001B<"
# key = "Comma"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001B_"
# key = "Minus"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001B%"
# key = "Key5"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001B^"
# key = "Key6"
# mods = "Alt|Shift"
#
# [[keybindings]]
# chars = "\u001B\\"
# key = "Backslash"
# mods = "Alt"
#
# [[keybindings]]
# chars = "\u001B|"
# key = "Backslash"
# mods = "Alt|Shift"
#
[font]
size = 13.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
option_as_alt = "Both"
opacity = 0.65

