[git_branch]
symbol = "🌱 "
truncation_length = 12
truncation_symbol = ""

[git_state]
progress_divider = " of "
cherry_pick = "🍒 PICKING"

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷"
stashed = "📥"
modified = "📝"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "👅"
deleted = "🗑"

[character]
symbol = "λ"
error_symbol = "✗"
use_symbol_for_status = true
