theme = "onedark"

[editor]
line-number = "relative"
mouse = false
rulers = [88, 120]
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

