# https://taskfile.dev

version: "3"

tasks:
  luacheck:
    desc: Run luacheck for static analysis
    cmd: luacheck --quiet --codes --ranges .

  stylua:
    desc: Check formatting with stylua
    cmd: stylua --check .

  stylua-fix:
    desc: Fix formatting with stylua
    cmd: stylua .

  lint:
    desc: Run all linting checks (luacheck + stylua)
    deps: [luacheck, stylua]

  fmt:
    deps: [stylua-fix]

  load-default-keymap:
    desc: loads default keymap from lazyvim repo
    cmd: curl -sSl https://raw.githubusercontent.com/LazyVim/LazyVim/refs/heads/main/lua/lazyvim/config/keymaps.lua
