---
templates:
   params:
      author-email: edvard@majakari.net
      author-name: Edvard Majakari
      category: CLI
      copyright: Edvard Majakari
      github-username: edvardm

system-ghc: true
install-ghc: true
allow-newer: false
ghc-options:
  "$locals": -j
